# Generated by Django 4.1.2 on 2022-10-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inya', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='title',
            field=models.TextField(verbose_name='タイトル'),
        ),
    ]
