# Generated by Django 4.1.2 on 2022-10-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inya', '0003_search_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='limit',
            field=models.CharField(default=1, max_length=30, verbose_name='制限時間'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='search',
            name='memo',
            field=models.CharField(max_length=30, verbose_name=30),
        ),
    ]
