version: "3"

services:
    database:
        image: postgres
        env_file:
            - ".env"
        restart: always
    
    web:
        build: .
        env_file:
            - ".env"
        volumes:
            - .:${APP_ROOT}
        links: 
            - database
        restart: always

    nginx:
        image: nginx
        env_file:
            - ".env"
        volumes:
            - ./nginx:/etc/nginx/conf.d/
            - static:$STATIC_ROOT
            - media:$MEDIA_ROOT
        links:
            - web
        ports:
            - "80:80"
        restart: always

volumes:
    static:
        driver: local
    media: 
        driver: local
