version: "3"

services:
    database:
        image: postgres
        env_file:
            - ".env"
        restart: always
    
    web:
        build: .
        env_file:
            - ".env"
        volumes:
            - .:${APP_ROOT}
        ports:
            - "80:8000"
        links: database
        restart: always

    nginx:
        image: nginx
        env_file:
            - ".env"
        volumes:
            - ./nginx.conf:/etc/nginx/templates/default.conf.template
            - static:$STATIC_ROOT
            - media:$MEDIA_ROOT
        links:
            - web
        restart: always

volumes:
    static:
        driver: local
    media: 
        driver: local
