# Generated by Django 4.1.2 on 2022-10-18 18:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nazo',
            fields=[
                ('title', models.CharField(max_length=30, verbose_name='タイトル文')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('difficulty', models.IntegerField()),
                ('input', models.CharField(max_length=10, verbose_name='入力方法指定')),
                ('minihint', models.TextField(verbose_name='ミニヒント文')),
                ('hint', models.TextField(verbose_name='不正解時ヒント文')),
                ('img', models.ImageField(upload_to='', verbose_name='謎解き画像')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_answer', models.CharField(max_length=20, verbose_name='入力内容回答')),
                ('answer', models.CharField(max_length=20, verbose_name='回答')),
                ('next_place', models.CharField(max_length=30, null=True, verbose_name='次の謎の場所')),
                ('img', models.ImageField(upload_to='', verbose_name='キー画像')),
                ('nazo_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nazo.nazo')),
            ],
        ),
    ]
