# Generated by Django 4.1.2 on 2022-10-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nazo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='border_color',
            field=models.CharField(default=1, max_length=10, verbose_name='答えのページの枠線の色'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(verbose_name='回答'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='next_place',
            field=models.TextField(null=True, verbose_name='次の謎の場所'),
        ),
    ]
