# Generated by Django 4.1.2 on 2022-10-23 09:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nazo', '0002_answer_border_color_alter_answer_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='id',
        ),
        migrations.AddField(
            model_name='answer',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='img',
            field=models.ImageField(upload_to='answer/', verbose_name='キー画像'),
        ),
        migrations.AlterField(
            model_name='nazo',
            name='img',
            field=models.ImageField(upload_to='nazo/', verbose_name='謎解き画像'),
        ),
    ]
