# Generated by Django 4.1.2 on 2022-10-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nazo', '0003_remove_answer_id_answer_uuid_alter_answer_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='input_answer',
            field=models.CharField(max_length=30, verbose_name='入力内容回答'),
        ),
    ]
