# Generated by Django 4.1.2 on 2022-10-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nazo', '0004_alter_answer_input_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='keyword',
            field=models.CharField(default=1, max_length=20, verbose_name='最終問題のキーワード'),
            preserve_default=False,
        ),
    ]
