# Generated by Django 4.1.2 on 2022-10-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nazo', '0005_answer_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='nazo',
            name='tutorial',
            field=models.BooleanField(default=False, verbose_name='チュートリアル'),
        ),
    ]
