# Generated by Django 4.1.2 on 2022-10-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nazo', '0006_nazo_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nazo',
            name='last_nazo',
            field=models.BooleanField(default=False, verbose_name='最終問題'),
        ),
    ]
