# Generated by Django 4.1.2 on 2022-10-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nazo', '0008_nazo_big_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='next_place',
            field=models.TextField(blank=True, null=True, verbose_name='次の謎の場所'),
        ),
    ]
